### ISSUE TITLE
Add to Modrinth

### ISSUE THREAD

**Issue by sylv256** [MehVahdJukaar/WoodGood#106]
Please add this mod to Modrinth to make it easier for modpack creators etc. on Modrinth.
An increasing number of mods are moving to Modrinth, especially as they recently added monetization support. Modrinth is a platform with better searching, API, and features for mod developers, and their community and developers are very welcoming to developers.

**Comment by MehVahdJukaar** [comment]
I am aware of modrinth and I'll move there at my own pase. I already have some mods there but uploading over multiple sites is painful. Supporting multiple versions is annoying enough. As for the monetization I know and it's not much of an incentive since low amount of modopacks mean the outcome is negligible compared to cf
