### ISSUE TITLE
1.18.2 did not load some mods items

### ISSUE THREAD

**Issue by Dr-WeiAL** [MehVahdJukaar/WoodGood#112]
Storage Drawers, for example, which is displayed normally in 1.19.2, but not in 1.18.2
There are a lot of mods items that don't show up in 1.18.2
![image](https://user-images.githubusercontent.com/47446553/206904074-ecacb28f-5b6b-419c-b2cc-3330724e9873.png)
1.18.2

![image](https://user-images.githubusercontent.com/47446553/206904223-e84a96bf-ba83-46f1-ab4d-bf59978f0c59.png)
1.19.2

**Comment by MehVahdJukaar** [comment]
That's simply because they were added in 1.19

**Comment by Dr-WeiAL** [comment]
> That's simply because they were added in 1.19

![image](https://user-images.githubusercontent.com/47446553/206948851-5af21b2d-2c29-49e5-8afd-502e2a5c30dd.png)
Okay, so that means that the Optional Dependency is wrong here?

**Comment by MehVahdJukaar** [comment]
Could be wrong but cueseforge might put them on a per project basis

**Comment by joe-vettek** [comment]
![image](https://user-images.githubusercontent.com/82761814/208426736-ce328f45-a675-4605-8e95-b7f11ff7bd37.png)
Can I use this way to add them?

**Comment by MehVahdJukaar** [comment]
That can just generate recipes and is in 1.18 only

**Comment by Xelbayria** [comment]
@joe-vettek 
Just to be clear, **Storage Drawer** is not supported in 1.18.2 but it's supported in 1.19.2 and newer versions. The alternative is to use an addon that does the same as Every Compat did for 1.18.2: [More Storage Drawers](https://www.curseforge.com/minecraft/mc-mods/more-storage-drawers)

I'll be closing this since it's an old issue. If you wish to discuss more, then you can continue commenting here.
