### ISSUE TITLE
Nether's Exoticism Jabuticaba compat blocks spelling error

### ISSUE THREAD

**Issue by saltyseadoggo** [MehVahdJukaar/WoodGood#164]
The hedge and leaf carpet this mod adds for Nether's Exoticism's Jabuticaba wood type are erroneously named `Jaboticaba` instead of `Jabuticaba`. All of the other blocks this mod adds for this wood type have their names spelled correctly.

**Comment by MehVahdJukaar** [comment]
That's because the mod itself has their IDs like that

**Comment by saltyseadoggo** [comment]
While that is mostly true (some blocks and items from NE have the correct spelling in their ids), I don't believe that constitutes a reason to leave this issue as is, especially when, according to my testing, it seems impossible for an end user to fix the spelling error with a lang file change due to the way this mod handles item names.

**Comment by MehVahdJukaar** [comment]
Yes that mod was a mess. IDs were inconsistent and with such spelling mistakes and texture paths were too. Must be because it's mcreator. Changing the name of any block is trivial. Just add a Lang string for that specific block like you would normally. Or you could also add wood_type.netherexoticism.jabutica Lang string for the entire wood type

**Comment by Xelbayria** [comment]
What version is the issue currently in?

**Comment by Xelbayria** [comment]
Is this issue resolved? If there are no responses for a week from now. then this will be closed.
