### ISSUE TITLE
TF Quark posts are named inconsistently with other blocks of their wood types

### ISSUE THREAD

**Issue by saltyseadoggo** [MehVahdJukaar/WoodGood#190]
Some of the Quark posts this mod adds for Twilight Forest are named inconsistently with other blocks of their wood types. They are as follows:
- `Mining Post` should be `Minewood Post`
- `Transformation Post` should be `Transwood Post`
- Ditto for their stripped versions

Timewood, darkwood, sortingwood, twilight oak, canopy and mangrove posts and their stripped counterparts all have correct names.

**Comment by Xelbayria** [comment]
if this problem still persists, then please fill in the following:
Minecraft Version:
Loader: (Forge or Fabric)
EveryCompat (EC) Version:
Which Mods does EC have an issue with:

otherwise, please close this issue, thanks!

**Comment by saltyseadoggo** [comment]
i have tested to confirm that the issue still exist.
minecraft 1.19.2
forge 43.2.8
moonlight lib 2.2.46
every compat 2.5.10

mods involved with the issue:
autoreglib 1.8.2-55
quark 3.4-414
twilight forest 4.2.1518

**Comment by Xelbayria** [comment]
alright, I'll look in this

**Comment by MehVahdJukaar** [comment]
This can be fixed by adding custom translations for those wood types on the Lang. Weird I thought I already had them

**Comment by Xelbayria** [comment]
alright, I'll check the EN_US to make sure everything is good

**Comment by Xelbayria** [comment]
@MehVahdJukaar 

> This can be fixed by adding custom translations for those wood types on the Lang. Weird I thought I already had them

Ok. I've investigated the EN_US and it is quite strange. <strike>Can you tell me what's going on? 

here's from my side. There are 4 woods from **The Twilight Forest**: 
- **Darkwood** Log
- **Timewood** Log
- **Transwood** Log
- **Sortingwood** Log

The other wood types are **Minewood**, **Canopy**, **Twilight Oak**, and **Mangrove**.  They do not have a Log or stripped Log. 
Just furniture: 
- stairs
- slabs 
- fences 
- so on and on
</strike>

--- 

# Ignore above. 

I understand what's the problem. The reason why these 2 woods: Minewood & Transwood used the wrong naming is due to the ID: `transformation_<block>` & `mining_<block>`. it seems the system used that as a base name. It's the same for other blocks.

**Comment by Xelbayria** [comment]
Fixed & will be in the next version later
