### ISSUE TITLE
[🐞]: Texture issues with Terraqueous cloud blocks.

### ISSUE THREAD

**Issue by CsillaAria** [MehVahdJukaar/WoodGood#262]
I don't know if you can even do anything about it, but some of the items made from the cloud blocks from Terraqueous have oak textures in some places.  I have a screenshot of what I'm talking about here:
![2023-09-19_17 12 02](https://github.com/MehVahdJukaar/WoodGood/assets/77200112/1a3a03ed-2e6b-4986-beac-b2103eb10291)

**Comment by Xelbayria** [comment]
i'll need the following information:
- Which version
- Which loader 
- Version of EveryCompat (EC)
- which mod that EC has an issue with
- Which mod that add wood_type: Terraqueous (correct?)

**Comment by CsillaAria** [comment]
I'm using Minecraft 1.20.1 
forge version 47.1.3 
everycomp-1.20-2.6.7
terraqueous-forge-1.20.1-1.1

The wood type blocks are the cloud blocks: light cloud, dense cloud, and storm cloud. I'm wondering if the issue is because they aren't typical wood blocks? So I'm not sure if there really is anything that can be done about it. Sorry I know absolutely nothing about modding. I hope this helps.

**Comment by Xelbayria** [comment]
> I'm using Minecraft 1.20.1 forge version 47.1.3 everycomp-1.20-2.6.7 terraqueous-forge-1.20.1-1.1
> 
> The wood type blocks are the cloud blocks: light cloud, dense cloud, and storm cloud. I'm wondering if the issue is because they aren't typical wood blocks? So I'm not sure if there really is anything that can be done about it. Sorry I know absolutely nothing about modding. I hope this helps.

one last question you forgot to answer `which mod that EC has an issue with`

in the picture, there is a purple/black textured block, 2 of them. which mod are they from?

**Comment by CsillaAria** [comment]
Sorry, those are from Chipped. The version of chipped I'm using is 1.20.1-3.0.1

**Comment by Xelbayria** [comment]
> Sorry, those are from Chipped. The version of chipped I'm using is 1.20.1-3.0.1

alright, thank you. I'll do some investigation to find out what's going on

**Comment by Xelbayria** [comment]
@MehVahdJukaar 

This is quite strange. I've investigated this. Three blocks are missing the texture (I checked the debug folder). The textures weren't generated. 

Two blocks from Chipped are: 
- Polished \<type> Planks
- Brick Bond \<type> Planks
- \<type> Planks Panel (since **Terraqueous v1.1.2**)
- Crated \<type> Planks (since **Terraqueous v1.1.2**)
- Enclosed \<type> Planks (since **Terraqueous v1.1.2**)

Three blocks from Terraqueous are:
- Light Cloud
- Dense Cloud
- Storm Cloud

I also checked with Biomes O' Plenty, there were no issues at all. The log showed this: 

```
[18:37:23] [Render thread/ERROR]: Failed to generate texture everycomp:block/ch/terraqueous/storm_cloud_planks/brick_bond_oak_planks: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
[18:37:23] [Render thread/WARN]: Could not generate texture everycomp:block/ch/terraqueous/storm_cloud_planks/brick_bond_oak_planks
[18:37:23] [Render thread/ERROR]: Failed to generate texture everycomp:block/ch/terraqueous/dense_cloud_planks/brick_bond_oak_planks: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
[18:37:23] [Render thread/WARN]: Could not generate texture everycomp:block/ch/terraqueous/dense_cloud_planks/brick_bond_oak_planks
[18:37:23] [Render thread/ERROR]: Failed to generate texture everycomp:block/ch/terraqueous/light_cloud_planks/brick_bond_oak_planks: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
[18:37:23] [Render thread/WARN]: Could not generate texture everycomp:block/ch/terraqueous/light_cloud_planks/brick_bond_oak_planks
```

**Comment by CsillaAria** [comment]
Weird. Thank you for looking into it though!

**Comment by Xelbayria** [comment]
<strike>
Ok. New details: 

I checked the texture of these: **Light Cloud**, **Dense Cloud**, **Storm Cloud**. they all have 5 colours. it must be at least 7 colours. 

that is the cause of the problem above.  that's not all. in the newer version of **Terraqueous**, *v1.1.2*,  3 more blocks have no textures: 
- \<type> Planks Panel (since Terraqueous v1.1.2)
- Crated \<type> Planks (since Terraqueous v1.1.2)
- Enclosed \<type> Planks (since Terraqueous v1.1.2)

EDIT: 
you should speak to the dev of the mod to see if the number of colours for these 3 clouds could be increased to 7 colours. </strike>

**Comment by Xelbayria** [comment]
Ignore above. it turned out it was a mistake on my side. I'm not familiar with working with textures via coding. this is why it took some time. I finally understand what's the root of the problem and it's fixed.
