### ISSUE TITLE
[🐞📦]: Dramatic Doors 3.1.0 has major API breaks

### ISSUE THREAD

**Issue by brisingraerowing** [MehVahdJukaar/WoodGood#284]
### Version

1.19.2

### Loader

Forge

### EveryCompat Version

2.5.10

### Moonlight Lib Version

2.2.46

### Issue with mods

Dramatic Doors 3.1.0

### Issue Detail

Dramatic Doors 3.1.0 completely restructures the mod to be multiloader in one file. This results in a crash from this mod on startup.

### To Produce

Load this mod with Dramatic Doors 3.1.0

### Optional Attachment

[Game output log](https://gist.github.com/brisingraerowing/d4b5cf22e02333bb246f67013408da70)

Crash is near the middle.

**Comment by Xelbayria** [comment]
this is to be expected. I've been in discussion with the guy who worked on the mod. The new version of Dramatic Door is a major version (big change). I recommend you to downgrade to the previous version for now.

**Comment by brisingraerowing** [comment]
Already did.

**Comment by Xelbayria** [comment]
~~Can I get the filename including the version of Dramatic Door?  it should have `QuFabrge` in it. I cannot find v3.1.0~~

wait, did you get it from discord or github?

**Comment by brisingraerowing** [comment]
https://www.curseforge.com/minecraft/mc-mods/dramatic-doors/files/4800451

**Comment by Xelbayria** [comment]
## Details: 
Major API breaks are expected because the update is a major update. 
Required the Module to be changed to account for the major change & included Mod supported. 

**Mod Supported List:** 
- blueprint
- abundant_atmosphere
- ad_astra
- aether
- aether_redux
- architects_palette
- atum
- bambooeverything
- betterarcheology
- betterend
- betternether
- bewitchment
- biomancy
- biomemakeover
- biomesoplenty
- blocksplus
- blockus
- byg
- caupona
- ceilands
- charm
- cinderscapes
- cobblemon
- colorfulazaleas
- copperoverhaul
- alloyed
- createdeco
- create_things_and_misc
- darkerdepths
- deeperdarker
- desolation
- dustrial_decor
- ecologics
- endlessbiomes
- enhanced_mushrooms
- phantasm
- enderscape
- enlightened_end
- everythingcopper
- extendedmushrooms
- fruittrees
- forbidden_arcanus
- gardens_of_the_dead
- goodending
- graveyard
- hexcasting
- hexerei
- horizons
- integrateddynamics
- malum
- glassdoor
- ms
- morecraft
- mysticsbiomes
- nethers_exoticism
- newworld
- pokecube
- prehistoricfauna
- premium_wood
- promenade
- pyromancer
- quark
- regions_unexplored
- silentgear
- snowyspirit
- supplementaries
- tconstruct
- techreborn
- terraqueous
- terrestria
- traverse
- twigs
- twilightforest
- undergarden
- wilderwild
- windswept
- xps_additions
- yippee
- chipped
- mcwdoors
- manyideas_doors
- quark

**Comment by drakray** [comment]
Probably related, crash on 1.20.1 too (DD 3.1.0 for 1.20.1) https://pastebin.com/CMP6be9v

**Comment by Xelbayria** [comment]
@drakray 
No worries. that's blc DD 3.1.0 has a major update with huge changes.

**Comment by Xelbayria** [comment]
## ATTENTION: 

**If anyone has a similar report like this issue, just downgrade to the previous version for now.** 

**Note:**
There will be an update to the Dramatic Doors Module via Every Compat. Please be patient.  The major update of DD is to be able to support Fabric, Forge, and quilt (all in one jar). There are no changes to the contents of DD. 

In other words, you are not missing out on anything.

**Comment by brnbrd** [comment]
I submitted #289 to fix the crash for Forge. This module could seemingly be easily extrapolated to support Fabric as well.

**Comment by Xelbayria** [comment]
Now we need to do the same for 1.20.1

**Comment by slickritalin** [comment]
Hey I was just wondering when the 1.20.1 fix for this is going to drop

**Comment by Xelbayria** [comment]
> Hey I was just wondering when the 1.20.1 fix for this is going to drop

The fix has been applied to EC. You can check out the Curseforge. the current version is **2.6.12**,   the fixes was applied in v2.6.10.

**Comment by Xelbayria** [comment]
Guys, 
I'll update **Dramatic Doors Module** module for the new version of **Dramatic Doors** v3.1.2 (it's currently being backported from 1.20.1). Just waiting for the developer to let me know it's done. I'll update the module.

**Comment by slickritalin** [comment]
> The fix has been applied to EC.

Ah it must be something else breaking EC, I'll work it out and open a new issue.
