### ISSUE TITLE
[🐞]: Chipped does not add bookshelf variants to woodster bookshelves

### ISSUE THREAD

**Issue by dadobug1111** [MehVahdJukaar/WoodGood#362]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.18

### Moonlight Lib Version

moonlight-1.20-2.8.67

### Issue with mods

Chipped-1.20.1-3.0.1
Woodster-1.4.5

### Issue Detail

Chipped adds several bookshelf variants to the base (oak) bookshelves. Every Compact does not yet extend them to bookshelf wood types added by Woodster .

**Comment by Xelbayria** [comment]
Can you check to see if Woodster's Wood Type has the sound "Bass"? 

Wait a min, IIRC **woodster** doesn't have any wood types

**Comment by dadobug1111** [comment]
Woodster adds bookshelves for all wood types. chipped bookshelf variations are not generated for these new shelves.

**Comment by Xelbayria** [comment]
> Woodster adds bookshelves for all wood types. chipped bookshelf variations are not generated for these new shelves.

[ Deleted ]

EDIT: 

Ok, i am confused. Can you clarify what you said. 

From what I understand is that 
**Woodster** have:
- Bookshelf
- Chiseled Bookshelf
- no wood types. 

**Chipped** have: 
- Types of planks,
- Others.
- no wood types. 

**Every Compat** is not designed to combine the blocks between **Woodster** & **Chipped** because they don't have Wood types. It's designed to combine a block (Furniture or block) from one mod with Wood Types from mods like **Biomes O' Plenty**

**Comment by dadobug1111** [comment]
![2023-12-12_18 03 38](https://github.com/MehVahdJukaar/WoodGood/assets/33583954/29ed99a3-f019-4f10-b3aa-37cc55107509)

Chipped adds variants for **Oak Bookshelves**, the only bookshelf type present in vanilla.
It does not add these variants for other wood types.


![2023-12-12_18 03 58](https://github.com/MehVahdJukaar/WoodGood/assets/33583954/9eb3c539-c218-4ad8-9658-197c9c546726)
Woodster adds bookshelves for **All Vanilla Wood Types**. Every Compact extends this to any new wood types.

The suggestion is to add chipped bookshelf variants to all loaded wood types when Woodster is also loaded.

**Comment by Xelbayria** [comment]
Ah, I understand the problem. Thanks for the clarification. Hmm, when since did **Chipped** add new blocks, "Bookshelf". 

EDIT: 
I see what's going on. The reason why Bookshelf wasn't added is because Chipped only has one wood type: Oak for Bookshelf. that's it. 

Woodster Module supported _Chiseled Bookshelf_ & _Bookshelf_ and it should be loaded with wood types from any mods. Thanks to your report (not related), I found some problems with the module and applied some fixes, 

EDIT 2: 
I forgot to mention. there are 33 types of Bookshelf and if it's added. It could lead to Minecraft exploding (in other words, crashing due to not enough RAM or whatever)

**Comment by Xelbayria** [comment]
@MehVahdJukaar 
is it fine to add Bookshelf (33 types) to module. If it's too much, one could disable it from being added via **Every Compat (EC)**'s Config? or Nah?
I wasn't able to decide whether should i close this issue or add the 33 types of bookshelf to **EC**

**Comment by MehVahdJukaar** [comment]
I'm not sure

**Comment by Xelbayria** [comment]
### UPDATE: 

Well, the decision is to not add 33 types of Bookshelf to EveryCompat.  3 reasons: 
1) 33 x 6 woodTypes from a wood mods = 198 blocks. The more woodTypes, the greater the number will be. 
2) I added stripped_log and log (they each 9-11 blocks) which is okay-ish. 
3) if 33 bookshelf can be reduced to one block using 33 different textures. This is possible in other mods. You could let the author know about it. if he change it to 1 bookshelf with 33 different textures using a _Carpenter's Table_. 

then I can add it to EveryCompat. and if he could do same with other blocks. and then I can add all of them to EveryComp. It could reduce the resources by adding 1 block with 33 different textures compared to add blocks to Minecraft. 

The amount of blocks added by **Chipped** & **EveryComp** is quite high depending on wood mods. That's all.
