### ISSUE TITLE
[🐞]: Quark x Gardens of the Dead produces incorrect Hollow Log/Post

### ISSUE THREAD

**Issue by DJBaphomet** [MehVahdJukaar/WoodGood#423]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

Every Compat 1.20-2.6.28

### Moonlight Lib Version

Moonlight Lib 1.20-2.9.7

### Issue with mods

- Gardens of the Dead v4.0.1
- Quark v4.0-432.3268

### Issue Detail

Due to how Every Compat works, it produces the Hollow Log/Post variants from Quark for Whistlecane, which functions just fine
However, because Whistlecane takes after bamboo, the "log" that Every Compat tries to use is the base Whistlecane item itself, producing incorrect textures (I believe it's taking after the "leaves" texture of the whistlecane block)
![image](https://github.com/MehVahdJukaar/WoodGood/assets/44253613/23f94efd-6f6d-4624-aa5b-ba607c6fd28f)

Since Whistlecane now takes after bamboo in 1.20, it actually has a proper "log" to use for Every Compat, though there's no stripped variant of the Block of Whistlecane like there is for the vanilla bamboo. Every Compat _seems_ to recognize this as there's no Stripped Post for Whistlecane, and might be what causes the inside of the Hollow Log to just default to stripped oak,

As an extra note, seems to be the same issue that [#337](https://github.com/MehVahdJukaar/WoodGood/issues/337) is encountering, though I made a unique post since that one doesn't regard Quark

**Comment by Xelbayria** [comment]
You may want to check this out [Issue with the solution](https://github.com/MehVahdJukaar/WoodGood/issues/133) and see if it solved your problem. 

The short version is that you need to make a copy of the wood log and rename it with "stripped" which the block expected to find. Put it in your resource pack. 

I'll look into the problem of why the block defaulted to "stripped Oak log"

**Comment by DJBaphomet** [comment]
Attempted what was mentioned in there, tried both "whistlecane_log_top.png" and "stripped_whistlecane_log_top.png" using [this texture](https://github.com/ochotonida/gardens-of-the-dead/blob/1.20.x/common/src/main/resources/assets/gardens_of_the_dead/textures/block/whistlecane_block_top.png), though it didn't work. 
Also tried "whistlecane_block_top.png" and "stripped_whistlecane_block_top.png", as well as variants with "wood" instead of log/block, and none of those worked either

I may also just be doing something wrong, but I followed the filepath shown near the end exactly, and did the same thing, so I'm not sure if it works due to the uniqueness of whistlecane's situation


However, even if this did work, I'm not sure it'd impact the outside of the hollow log, which seems to be directing to [this texture](https://github.com/ochotonida/gardens-of-the-dead/blob/1.20.x/common/src/main/resources/assets/gardens_of_the_dead/textures/block/whistlecane_leaves0.png) instead of the whistlecane block texture

**Comment by DJBaphomet** [comment]
As an extra note, since I just thought to test: This also happens in a 1.19 instance as well, so it's not solely a 1.20 problem
![image](https://github.com/MehVahdJukaar/WoodGood/assets/44253613/33e4abff-ba93-475f-ad3b-fa357117136f)
(screenshot taken with Abundant Atmosphere and Windswept!'s woods in the background because I just opened a quick 1.19 instance I already had to test this)

This is before Whistlecane's blockset was adjusted in the 1.20 version to mimic vanilla's bamboo blockset as well, so that's not the culprit

**Comment by Xelbayria** [comment]
I see. that's great info regarding **v1.19.2**. I'm investigating this. I'll share what I find out in here.

**Comment by Xelbayria** [comment]
Ok. it looks like i may have to add "children check" to check if the wood has stripped_log, and then it will create the block. otherwise, it won't create the block. 

It turned out the problem was not the texture part. it's the required block that has the texture.  You said Whistlecane doesn't have the stripped_log (along with the texture). 

EDIT:
if I add the "children check" to the mod, it will remove the block existing in your world. Will that be fine. there is no solution. the problem is not on **EC**. The problem is with the dev's mod. The dev can choose to add stripped_log or not. you need to contact the dev.  

EDIT2: 
<strike>can you give me the resource pack with the texture for Whistlecane's stripped stuff.</strike> I got an idea. 

EDIT 3:
oh wow. this mod, **Gardens of the dead** is "tsk". The problem is worse than I thought. The name of these files for **whistlecane** textures are all messed up.  it's not within the minceraft ID format for these textures of Bamboo. 

i gotta change my idea and run another test. don't worry about the resourcepack.

**Comment by Xelbayria** [comment]
good news: 
my idea works. and you don't need to worry about the resource pack or anything. You may want to speak to the dev of **Gardens of the dead** about the filename format problem with _whistlecan_, it needs to be fixed. just change `whistlecane_block` to `whistlecane_log` or "stem".   same for "_top". There are also `leaves0` and `leaves1`  I'm not sure why it's like that. it need to be fixed, too. 

that's why the "leaves0" texture shows up on the block instead of the correct texture. 

![Proof-Gardens-of_the-dead](https://github.com/MehVahdJukaar/WoodGood/assets/12866666/14179a38-8359-4d09-a48b-91427f176fc4)

EDIT 
Depends on the dev, if the fix won't be applied to the mod, then I'll add the fix to **EC** for now. 

EDIT2: 

forgot to mention this: "block" is why everycompat wasn't able to find the correct texture for the _whistlecane_.

that's it.

**Comment by Xelbayria** [comment]
#### Additional info
To clarify the problem, go to the `gardens_of_the_dead:textures/block/` and look for _whistlecane_ files for textures. Take a good look at a good look at their filenames. That is the problem
