### ISSUE TITLE
Current fabric update

### ISSUE THREAD

**Issue by saphsara** [MehVahdJukaar/WoodGood#441]
I did the update you put out for this and got an error . it is the only mod i updated . moonlight and every compact. 
![updated mod error](https://github.com/MehVahdJukaar/WoodGood/assets/33788318/b0de0ec0-3457-457f-b99d-004dca72cb1c)

_Originally posted by @saphsara in https://github.com/MehVahdJukaar/WoodGood/issues/438#issuecomment-1958777840_

**Comment by Xelbayria** [comment]
try to downgrade **Moonlight Lib** and see if that fixes the problem. The problem is in _datapack_ and it is outdated and it doesn't account for the changes that **Moonlight Lib** has.

EDIT:
FYI
The only changes in the latest version of **Every Compat** are just a fix to make sure the blocks have the correct texture. it's not a major. I checked **Moonlight Lib**'s Changelog via Curseforge and it has a major change in codes regarding the fluids stuff.

**Comment by saphsara** [comment]
it worked without updating moonlight lib. however when i updated another mod Supplementaries it is requiring an updated moonlight lib. just wanted to let you know. i am all set. I just left the 2 not updated, thank you for all the help and for being on top of everything. have a great day

**Comment by Xelbayria** [comment]
👍 if you want to use Supplementaries (latest version), you'll need to have that _datapack_ updated to account for the changes in **Supplementaries** & **Moonlight LIb**

have fun!

**Comment by saphsara** [comment]
Ok. I am not sure what that means. Would u mind explaining,  I know how to add mods and do some troubleshooting but that's as far a is goes. Thank you again for the information.

**Comment by Xelbayria** [comment]
> Ok. I am not sure what that means. Would u mind explaining, I know how to add mods and do some troubleshooting but that's as far a is goes. Thank you again for the information.

oh ok. _datapack_ are scripts where one can modify recipes or others. it's a Minecraft feature. It's limited compared to **CraftTweaker** or **KubeJS** with a ton of features aside from modifying recipes. It uses a JSON file. I'm not familiar with _data pack_ given what it's truly capable of. If you would like to know [More Details](https://minecraft.fandom.com/wiki/Data_pack).

the errors you see on the screen are pointing at the _data pack_ where one of the scripts is modifying something related to **Supplementaries** or **Moonlight LIb**, something to do with fluid stuff. that's my best guess.  If your modpack is not the custom modpack you made. then you can wait for someone to update the modpack with the latest 2 mods and corrected scripts.

**Comment by saphsara** [comment]
Thank you. I created the mod pack awhile ago by throwing a hunch of mods together , tested they worked and brought a server for friends to play on. I just update it as needed when it states mods are updated. I really have not a  clue beyond that. Thank you for all the support and expertise.  I will eventually figure it out slowly learning.

**Comment by saphsara** [comment]
ok i updated the mods and i am getting something new . sorry if i am driving you crazy. 
![crash](https://github.com/MehVahdJukaar/WoodGood/assets/33788318/6495c750-672e-4dfb-9a2d-26939e5c677a)
[crash-2024-02-22_18.02.26-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/14380225/crash-2024-02-22_18.02.26-client.txt)

**Comment by Xelbayria** [comment]
No worries. I am not crazy right now, lol.  Anyway, it looks like the issue is on **Amendments**, i've spoke to **MehVahdJukaar** about this problem. there is one mod that caused the problem. it has to be removed
**Carpeted Stairs & Slabs** aka `Carpeted-1.20-1.4-fabric`

The reason is the feature of **Carpeted** is merged into **Amendments** if you look at the description of **Carpeted Stairs & Slabs**. In other words, both mods are doing the same thing. that caused conflict.

**Comment by saphsara** [comment]
Ok thank you! I will.remove it. You are awesome!
