### ISSUE TITLE
[🐞]: Woodwork and Quark trapped chest incompatible 

### ISSUE THREAD

**Issue by Brakeable980** [MehVahdJukaar/WoodGood#447]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2

### Loader

Forge

### EveryCompat Version

2.5.19

### Moonlight Lib Version

2.3.6

### Issue with mods

Woodwork
Blue Skies

### Issue Detail

The trapped chests added by woodwork to Blue Skies chests lacks texture.
![IMG_20240229_162402](https://github.com/MehVahdJukaar/WoodGood/assets/156517359/d6aa43aa-b548-49bf-9950-96b955e2b0fa)

**Comment by Xelbayria** [comment]
interesting. The reason why Crystallized Chest exists without any problem. but the other doesn't have the recipe and cannot generate the texture chest due to Blue Skies already have chests.   the reason why Every Compat failed to generate the recipe is a conflicts with the recipe that **Blue Skies**'s Chest is using.   both are the same. 

🤔

**Comment by Xelbayria** [comment]
Good news, I understood the whole story of the problem. I've fixed the bug in 1.20.1. I'll apply the same fix to 1.19.2. too. it will be in next version. 

EDIT:
addition information: 
the fix is also applied to Quark (similar to Woodwork).
