### ISSUE TITLE
[Suggestion] Config to turn of certain modules

### ISSUE THREAD

**Issue by Illios42** [MehVahdJukaar/WoodGood#45]
I think it'd be really good to not only be able to differentiate between the wood kinds that are supported but also get the option to turn of support for a module instead.

My current problem is that there is a mod called Compat O Plenty that adds BoP support for Quark, but with textures for the chests I like a lot better. Yet I'd still like to be able to use the compat for Macaw's Doors in BoP wood kinds so i can't just turn off the EC support for the wood kinds completely. Being able to just turn off a Quark(/other mod) module would solve this pretty neatly and allow for more customization.

**Comment by MehVahdJukaar** [comment]
I can do that but be aware that reistration cannot depend on configs otherwise a server and a client with the same exact set of mods might not be able to connect to eachother. This means that like the ones I already have what would happen would just be that those blocks and their recipes become hidden. As for other Compat mods that is a bug and shouldn't happen. I'll look into it but as you might have noticed when Installing that everrycompst will try not to register blocks that that mod already had added

**Comment by Illios42** [comment]
I saw that the EC chests are not being shown so it's working as intended! Kinda smoothed brained while testing, very sorry about that bit (my defense: it was late lol). 
Also good to know about the registration thing, if it's just not possible on a technical level dw about it too much, though hiding them would already be sth I'd take anytime

**Comment by MehVahdJukaar** [comment]
Yeah no worries. I'll still ads a per module config, could be useful for some cases where one wants to quickly disable stuff form a mod assuming the vanilla stuff it adds are disabled for the same reason
