### ISSUE TITLE
[🐞]: Quark chest compat is incomplete

### ISSUE THREAD

**Issue by SynfulChaot** [MehVahdJukaar/WoodGood#499]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

1.20-2.6.52

### Moonlight Lib Version

1.20-2.11.12

### Issue with mods

Quark 4.0-441
Twilight Forest 4.3.2145
Blue Skies 1.3.31

### Issue Detail

When Quark has its Variant Chests enabled, and Every Compat has the related configs turned on, it won't generate any chests (or trapped chests) for Blue Skies or Twilight Forest with the exception of Blue Skies' Crystallized Chest.

I don't know if this is related in any way to #447, but this isn't missing textures but rather the entire chest being missing.

What's strange is that the Woodworks compat has no issue creating the chests from any mod I've found so far, including both Blue Skies and Twilight Forest.  Also that the Quark compat seems to have no issue with other mods and will generate chests for them (_at least_ true of The Undergarden, Eidolon, and Forbidden & Arcanus.

This oddness happens whether or not Woodworks is installed.

**Comment by Xelbayria** [comment]
Can I get a list of woodTypes from **The Twilight Forest** for the chests that aren't generated? I'll take a look at **Blue Skies**.

### UPDATE: 

Ignore above. I found the problem with the code.  The reason why chests for **Blues Skies** or **Twilight Forest** aren't generated is because both 2 mods already have their chests except trapped_chest. I've added an exception to this so only trapped_chest will be generated.  the default chests from 2 mods can be used to craft trapped_chest. 

### UPDATE#2: 

it's fixed and will be in the next version.
