### ISSUE TITLE
[📦]: Visual workbench compat

### ISSUE THREAD

**Issue by MikroChris** [MehVahdJukaar/WoodGood#517]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/visual-workbench

### FABRIC Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

500273

### Types

Not a block, but the crafting tables from every compat don't work with the mod visual workbench

### Optional Details

It would be cool if you add compat for that mod

**Comment by Xelbayria** [comment]
You should have read the description via Curseforge: 

```
Visual Workbench even works with crafting tables added by other mods. 
Support has to be manually enabled per block though. 
Many modded crafting tables are supported by default, those that are not 
can be added to a custom config file found at 
.minecraft/config/visual_workbench.json (not accessible from in-game). 
If you add a crafting table yourself and it doesn't work it likely just not possible to be supported 
by this mod.
```


> Many modded crafting tables are supported by default, those that are not can be added to a custom config file found at .minecraft/config/visual_workbench.json (not accessible from in-game).

it doesn't support EveryComp by default. You should try manually adding the ID of these _Crafting Tables_ to the list

EDIT:
on another note, EveryComp cannot add support to **Visual workbench** because it's a pure visual. that just means it only rendering the workbench's stuff (you can see what's being crafted, you get the idea), It does not add any blocks or items

EveryComp can only add an item or a block
