### ISSUE TITLE
[🗃]: Merging hollow logs

### ISSUE THREAD

**Issue by OminousDiscovery** [MehVahdJukaar/WoodGood#540]
### Version

Twilight Forest - 4.3.2508, 4.0-455

### Curseforge

https://www.curseforge.com/minecraft/mc-mods/quark https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest

### Details

I'm not sure if you do this but I think this mod should unify hollow logs from twilight forest and quark because it just adds a bunch of duplicates. 
Edit: I also just want to put that both hollow logs have the same exact model and can both be rotated the same ways
![image](https://github.com/MehVahdJukaar/WoodGood/assets/150559423/18b9d580-f0c4-45a0-b120-8c546f2bd08e)

**Comment by Xelbayria** [comment]
I'll check

**Comment by Xelbayria** [comment]
I've took a look at this. it's impossible to merge these 2 hollow_log because they are from 2 different mods. 
the vertical hollow_log is **Quark**
the horizontal hollow_log is **The Twilight Forest**. 

The only thing you can do is go to `everycomp-common.toml` to hide 1 of 2 hollow_log that you don't want to see on JEi or REI.
