### ISSUE TITLE
[🐞]: Every Compart Wood Good crashes

### ISSUE THREAD

**Issue by Muvilan** [MehVahdJukaar/WoodGood#567]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.18.2

### Loader

Forge

### EveryCompat Version

everycompat-1.18.2-1.6.4

### Moonlight Lib Version

selene-1.18.2-1.17.14

### Issue with mods

I don't know it (sorry for my ignorance reading logs).

### Issue Detail

I have every compat (wood good) along with other mods, so when i try them in creative mode the game crashes when sliding tabs in the inventory screen (key E), particularly when reaching the 4th section of the inventory. Is there any way to solve it?

### OPTIONAL: Latest.log | Crash-report Attachment

[crash report.txt](https://github.com/user-attachments/files/16326449/crash.report.txt)

### OPTIONAL: To Produce

1. Load into the world. 2. Open de inventory. 3. Click to the right arrow until reaching the 4th section. 4. Game crashes.

**Comment by Xelbayria** [comment]
Do u happened to have "Roughly Enough Item" installed?

**Comment by Muvilan** [comment]
> Do u happened to have "Roughly Enough Item" installed?

Yeah I used to have that mod, but it caused me problems with crashes too so I removed it

**Comment by Xelbayria** [comment]
I thought so.  That's because EveryComp is registering 0 block!  so when REI cannot find any block for EveryComp's icon via Creative Mode in inventory, the icon of "tab" u know? that leads to crash. You don't need EveryComp. 

there should be a log in latest.log that say `EveryComp registered 0 Blocks!!! You don't need it`. 


EDIT: 
the other solution is to find one wood mod (Biomes O' Plenty or The Twilight Forest, your choice). this way EveryComp will register plenty of blocks. You can use REI, too.

**Comment by Muvilan** [comment]
I see. I already tried Everycomp with Biomes and it worked perfectly. Thanks a lot!
