### ISSUE TITLE
[🐞]: Small bug

### ISSUE THREAD

**Issue by DoyaaHaze** [MehVahdJukaar/WoodGood#593]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.18.2

### Loader

Forge

### EveryCompat Version

everycomp-1.18.2-1.6.15

### Moonlight Lib Version

moonlight-1.18.2-1.17.15

### Issue with mods

Enlightend
Orcz
Missing Wilds

### Issue Detail

This happened
![image_2024-08-23_215411981](https://github.com/user-attachments/assets/7d9cfd35-26cb-4419-ab09-aa32ca564937)

**Comment by Xelbayria** [comment]
Interesting. going to investigate this.

**Comment by Xelbayria** [comment]
**Fixed in v1.6.16** - orcz won't be added blc they don't have stripped log. 

This is the second issue reported with a similar issue (another wood mod) 

### EDIT: 
I need to know if you want to keep them or remove them? 

### EDIT 2: 
ignore above. The rest are fixed. Orcz won't be included because it has no stripped_stem texture.
