### ISSUE TITLE
[📦]: Fantasy's Furniture

### ISSUE THREAD

**Issue by EdoEquin0x** [MehVahdJukaar/WoodGood#610]
# REASON: 

There is no vanilla wood variants in the mod. If you can get Dev to add OAK variant in the mod, I can add the mod to Every Compat. There is nothing I can do.

### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/fantasys-furniture

### FABRIC Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

fantasyfurniture

### Types

**Block:**
- Tables
- Stools
- Chairs
- Chandelier
- Bookshelves
- Big and Small Shelves
- Chest
- Door
- Wardrobes
- Wall Shelves
- Couch
- Desk

### Optional Details

This mod has different furniture sets based on themes such as elvish and nordic so you would only need to support the wood-based sets. Unfortunately though, the mod doesn't seem to be open source.

**Comment by Xelbayria** [comment]
> And probably some more

Please add more blocks to the list. I'll need to know how many blocks or items are there in the mod, thanks!

**Comment by EdoEquin0x** [comment]
Updated, hope I didn't forget any

**Comment by Xelbayria** [comment]
> This mod has different furniture sets based on themes such as elvish and nordic so you would only need to support the wood-based sets.

Interesting. I'll need to check it out. Thanks for finishing the list.

**Comment by Xelbayria** [comment]
there is no vanilla woods in the mod. (OAK, ACACIA so on...). The problem is (i'll try to keep it simple as I can.)

Every Compat **(EC)** detect any type of woods like "Cherry" or "blackwood". **EC** will look at the base like "oak_table". it will do the work to split "oak" and "table" and add the wood name that it has detected. it would look like "cherry_table" or "blackwood". 

Another problem is the mod has no LOG and PLANKS. If I understand correctly on how **EC** works. Above is just basically how it works. but it's a more deep than that. Right now, there's nothing I can do. 

I'll speak with MehVahdJukaar about the system regarding the unique wood names. If I'm correct about above, then that's the bad news. I'll keep you posted.

**Comment by Xelbayria** [comment]
I spoke with MehVahdJukaar. Unfortunately, I am correct & it will have to be abandoned.
