### ISSUE TITLE
[🐞]: Some Regions Unexplored branches can't be placed.

### ISSUE THREAD

**Issue by LenKagamine** [MehVahdJukaar/WoodGood#641]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

2.6.82

### Moonlight Lib Version

2.13.7

### Issue with mods

Regions Unexplored 0.5.6

### Issue Detail

Certain branches from the Regions Unexplored mod don't seem to be able to be placed on their respective log. Woods from Biome's O Plenty seem to work fine but many others like Glacian from Ad Astra or Apricorn from Cobblemon can't be placed at all. The setblock command works fine so the blocks do exist, it's just that the blocks can't be placed.

### OPTIONAL: To Produce

1. Place down the log of a wood type supported by Every Compat
2. Try to place a branch on the side of the log. Some branches may work but most will not.

**Comment by Xelbayria** [comment]
The only one thing I can think of because these blocks from 2 mods doesn't have the tag, "minecraft:logs" IIRC. 

will check. 

# UPDATE: 
I was half correct. It wasn't `#minecraft:logs`, it was `#minecraft:overworld_natural_logs` 

Apricorn don't have the mentioned tag. I also checked other log, _glacian_log_ and yup. It don't have the tag. 

_branches_ have a code that check for all of logs with that tag where it can be "placed" on.

There are 2 solutions to this: 

1) you can create your own resource pack and adding these woods with missing the tag in a JSON file. 
2) You can let Devs of these 2 mods know about the missing tags of these woods.

**Comment by Xelbayria** [comment]
There is nothing I can do about this. Closing this. You can use 1 of 2 solutions mentioned above. 

and more: 
3. You can use CraftTweaker to add the tags to the logs with the missing tag
4. You also can use KubeJS
