### ISSUE TITLE
[🐞]: Ars Nouveau's Flavors & Delight blue log cutting recipe 

### ISSUE THREAD

**Issue by Dominus-Sicarum** [MehVahdJukaar/WoodGood#670]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

Every Compat [1.20-2.6.87] 

### Moonlight Lib Version

 Moonlight Library [1.20-2.13.21]

### Issue with mods

- Ars Nouveau [4\.12\.4]
- Ars Nouveau's Flavors & Delight [1\.1\.1]
- Farmer's Delight [1\.20\.1\-1\.2\.5]

### Issue Detail

Ars Nouveau's and Farmer's Delight's addon [Ars Nouveau's Flavors & Delight](https://www.curseforge.com/minecraft/mc-mods/ars-nouveaus-flavors-delight) adds axe cutting board recipes for nouveau's logs.

For some ungodly reason Every Compat reverts blue archwood log's cutting recipe back to Farmer's Delight default one (i.e. you're getting blue stripped log and bark, instead of blue stripped log and blue bark).

**Comment by Dominus-Sicarum** [comment]
It seems everycompat just adds cutting recipe for blue log only and it has priority over others.

**Comment by Xelbayria** [comment]
<strike>This is an easy fix. I simply have to add a compat mod like `Ars Nouveau's Flavors & Delight` to the list so EveryCompat should skip it </strike>

**Comment by Xelbayria** [comment]
Ignore above. 
I misunderstood your description of the issue. 

it's working fine. there is no variant wood for "tree_bark". note the ID of the bark is `farmersdelight:tree_bark`. That's a "universal bark" for any wood log. 

> adds cutting recipe for blue log only and it has priority over others.

That's because **Ars Nouveau** has one plank named `archwood_planks` which are used by other logs: blue, red, green...

there is no solution to fix this. blue_archwood_log is chosen as the supported wood for EveryCompat to use. 

red, green, OR yellow from **Ars Elemental**. Yellow also used archwood_planks, too. 👈🏻 are all skipped. There is a good reason for this. 

not much I can do.
