### ISSUE TITLE
[🐞]: [1.21.1] After installing the latest version of EveryComp there is a performance decrease and world may not load.

### ISSUE THREAD

**Issue by Periam** [MehVahdJukaar/WoodGood#687]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader

1.21.1-NEOFORGE

### EveryCompat Version

Every Compat 1.21-2.7.3 (everycomp)

### Moonlight Lib Version

Moonlight Lib 1.21-2.17.2 (moonlight)

### Issue with mods

This is a dump all the mods that you can to get it to crash-run to find incompatibilities.

### Issue Detail

There is a performance issue, initially with a previous versions of moonligth, the world loaded but it took a while to load the inventory for the first time when it was open. with latest version the performance got worst since the world do not load and the world may crash do to not enough memory.
 

### OPTIONAL: Latest.log | Crash-report Attachment

[latest-ecerycompact.log](https://github.com/user-attachments/files/17759047/latest-ecerycompact.log)

**Comment by Xelbayria** [comment]
> do to not enough memory.

that mean you do not allocate enough RAM to the Minecraft. Did you add a new mod like Wood mods (Biomes O' Plenty) or Furniture mods (Chipped, macaw's mod)? 

If you added Resource Pack, then yeah it required enough RAM to run. 

EDIT: 
I took a look at the log, I see **Chipped** is included. You may want to exclude it because it has a ton of blocks and try create a new world to make sure you have no problem. 

I think there are some modules that are outdated and need updating.

**Comment by Periam** [comment]
I did add all those mods, also a 64bit resource pack, and allocated 30gb ram.
If I disable the Everycompat I can play without any issue... 

I will try to run it without chipped..

What do you mean with:
I think there are some modules that are outdated and need updating.

**Comment by Xelbayria** [comment]
> What do you mean with:
I think there are some modules that are outdated and need updating.

What i mean is the modules in EveryCompat are what supported mods. Some of them haven't updated for 1.21.1 and are still using 1.20.1. Sometimes Mods updated from 1.20.1 to 1.21.1 with so little changes. They are fine. 

However, some have big changes will require the module to be updated.

**Comment by Xelbayria** [comment]
I ran a test with **Chipped** & **EveryCompat** via 1.21.1-NEOFORGE. I had no problem.

it looks like one of the mods is screwing up the asset generation that **EveryCompat** are trying to generate for blocks from supported mods. 

Can you disable all of the supported mods and enable 1-2 mods at a time until you got error in the log. an Error like spamming log about "Missing model" or whatever.

**Comment by Periam** [comment]
I will start testing what you are telling me.
I am now testing the pack without chipped an rechiseled: chipped.
These will take time >D 

Edit: did you tried famers delight?

**Comment by MehVahdJukaar** [comment]
sounds like you are just running out of ram. allocate more

**Comment by Xelbayria** [comment]
> Edit: did you tried famers delight?

i'll check on my side. 

## UPDATE: 

no problem with Farmer's Delight.

**Comment by Periam** [comment]
Can you list the main mods that yours works with?
I created a modpack with BOP, BWG, Refurbished,  the twilight forest to test but it worked fine..

**Comment by Xelbayria** [comment]
that was from last week. From what I remember: 
- EveryComp
- Moonlight Lib
- Farmer's Delight
- EMI
- Biomes O' Plenty (has 13 woodTypes) 

it's a simple modpack to run test. You have no problem on your side. it looks like one of the mod is decrease the performance. I've seen a case where a mod have a bad design of code that can impact performance in 1.19.2 but Dev improved it in 1.20.1. Can you try and find which one of the mods is the culprit? 

EDIT:
on another note, EMI does caused some a bit of laggy at the beginning then back to normal. it's because EMI was loading the recipes and stuff. 

EDIT 2: 
Another note: I've mentioned that Chipped should be excluded because it has ton of blocks. IIRC over 30 supported blocks. 🤔. You don't want to have too many blocks generated by EveryComp. Sometimes that can lead to laggy game due to not enough RAM. I remember you said you allocated 30GB and it wasn't enough. 

perhaps one of the mods have a huge impact on the performance. Something to look into.

**Comment by epilimic** [comment]
I tried adding this to ATM10 and the world wouldn't load for either my local machine nor the server.

**Comment by MehVahdJukaar** [comment]
You are running out of ram

**Comment by epilimic** [comment]
Doubtful on my local machine with 64gb, wild if so though. I've uninstalled just figured I'd share my experience here for others searching this issue out. Thank you.

**Comment by Xelbayria** [comment]
I've looked at ATM10's list of mods. It has ~10 or more wood mods. That can generate a lot of blocks. I don't think 16GB would be enough. That's not the worst part. There is **Chipped** mod in ATM10. 

Good idea to remove EC from ATM10, you have to play ATM10 as it is. If you want to use EC, you'll need to make your own modpack. Some of mods have addon that support wood mods. You could add them to ATM10 instead of using EC.

**Comment by MehVahdJukaar** [comment]
> Doubtful on my local machine with 64gb, wild if so though. I've uninstalled just figured I'd share my experience here for others searching this issue out. Thank you.

Your machine could have as much RAM as you want, if you dont allocate it to the game however you WILL run out of it

**Comment by Xelbayria** [comment]
## BRIEF: 

A few things to keep in mind: 
1) **Chipped**, 

If the modpack has it, then I don't recommend adding the **EC** to the modpack. You could look for addons that support a specific mod with other wood mods like (Farmer's Delight addons that support a few wood mods. IIRC **Chipped** has ~110 blocks supported by **EC**

2) RAM

Use F3 in-game, Look at the right, top side. The RAM you allocated to Minecraft as you are playing has to be between 50% to 75% (RAM being used during the game).

If you allocated too much RAM to Minecraft. say between 25% and 50% of RAM being used during the game. This could decrease performance. Too little or not enough RAM could lead to decreased performance OR Minecraft crashing due to "out of memory" 

I recommend you research this to find out how to determine the right amount of RAM being allocated to Minecraft

The modpack would required at least 8GB but with **EveryComp (EC)**, it would be at least 16GB depending on how many wood mods the modpack has. The ResourcePack also required RAM, too. 

---

The brief of this issue is that **EC** being suddenly added to an already built modpack. It's not recommended. Instead of **EC**, you could find addons that support wood mods for one furniture mod (Farmer's Delight or others). 

3 reasons: 
1) The modpack has **Chipped**
2) The modpack has over 10 wood mods
3) if you do the math, 10 wood mods which should have like 50 woodTypes. so 50 * 110 (chipped) = 5500 blocks. that's a lot of blocks and can take up a lot of RAM

**Comment by Xelbayria** [comment]
Closing this due to no active/no replying.
