### ISSUE TITLE
[🐞]: Stuck on the launch loading screen 

### ISSUE THREAD

**Issue by 3th3rr** [MehVahdJukaar/WoodGood#694]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader

1.19.2-FORGE

### EveryCompat Version

everycomp-1.19.2-2.5.29.jar

### Moonlight Lib Version

moonlight-1.19.2-2.3.7-forge.jar

### Issue with mods

im not sure

### Issue Detail

When every comp is added the game gets stuck on the launch loading screen.

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/user-attachments/files/17895165/latest.log)

**Comment by Xelbayria** [comment]
```
If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
```

You don't know which mods EveryComp have issue with... that's why You need to do ☝🏻 to find out which one of the supported mods is the culprit.

If you booted Minecraft with EveryComp and all of supported mods disabled just fine. That mean one of supported mod is causing the problem. We need to know which one. Otherwise, one of non-supported mods could also cause the problem.

**Comment by Xelbayria** [comment]
Any progress on this issue?

**Comment by Xelbayria** [comment]
Closing this due to no replying
